Pin Python to Python 2.7
ttbox is sadly still Python 2. Running on Python 3 will give an error
message like:

Traceback (most recent call last):
  File "ttbox", line 5, in <module>
    import ttbox_lib.cmdline as cmdline
  File "[...]/ttbox/ttbox_lib/__init__.py", line 1, in <module>
    from gme_raw_chunk import GmeRawChunk
ModuleNotFoundError: No module named 'gme_raw_chunk'

So we pin the used Python version to Python 2.7 (last Python 2
release) until we find time to make ttbox fit for Python 3.